#!/usr/bin/env bash

CURRENT_DIR=$(pwd)

if [ ! -d "${CURRENT_DIR}/repositories/default" ]; then
  echo "Missing the repository, run 'make default-init'"
  exit
fi

read -p 'Repository: ' repository
read -p 'Reason: ' reason
read -p 'Removal type: ' removal_type
read -p 'Link to more information: ' link

echo $repository
echo $reason
echo $removal_type
echo $link

cd "${CURRENT_DIR}/repositories/default"
python scripts/remove_repo.py "$repository" "$removal_type" "$reason" "$link" || exit 0