#!/usr/bin/env bash

CURRENT_DIR=$(pwd)

if [ ! -d "${CURRENT_DIR}/repositories/default" ]; then
  echo "Missing the repository, run 'make default-init'"
  exit
fi

cd "${CURRENT_DIR}/repositories/default"


# Pull latest
git pull upstream master