#!/usr/bin/env bash

if ! [ -x "$(command -v gh)" ]; then
  apk add go
  git clone https://github.com/cli/cli.git /srv/gh-cli
  cd /srv/gh-cli
  make
  mv ./bin/gh /usr/local/bin/

  if [[ $(git remote get-url origin) == *"git@github"* ]]; then
    gh config set git_protocol ssh
  fi
fi