#!/usr/bin/env bash

CURRENT_DIR=$(pwd)

if [ ! -d "${CURRENT_DIR}/repositories/integration" ]; then
  echo "Missing the repository, run 'make integration-init'"
  exit
fi

cd "${CURRENT_DIR}/repositories/integration"

# Run pytest
python -m pytest
