#!/usr/bin/env bash

CURRENT_DIR=$(pwd)

if [ ! -d "${CURRENT_DIR}/repositories/integration" ]; then
  echo "Missing the repository, run 'make integration-init'"
  exit
fi

cd "${CURRENT_DIR}/repositories/integration"

# Pull latest
git pull upstream master

# Install pacakges
python -m pip install -r requirements.txt